-- Nutrition: macro targets, meal planning + logging, and a recipe library.

-- ============================================================
-- 1. Recipe library (public, seeded)
-- ============================================================
create table if not exists public.recipes (
  id uuid primary key default gen_random_uuid(),
  slug text unique not null,
  title text not null,
  category text not null,
  image_url text,
  description text,
  calories int not null default 0,
  protein_g int not null default 0,
  carbs_g int not null default 0,
  fat_g int not null default 0,
  servings int not null default 1,
  prep_minutes int not null default 15,
  tags text[] not null default '{}',
  ingredients text[] not null default '{}',
  steps text[] not null default '{}',
  created_at timestamptz not null default now()
);
create index if not exists recipes_category_idx on public.recipes (category);

alter table public.recipes enable row level security;
drop policy if exists "anyone signed in reads recipes" on public.recipes;
create policy "anyone signed in reads recipes" on public.recipes
  for select to authenticated using (true);

-- ============================================================
-- 2. Daily macro targets (auto-suggested, user-editable)
-- ============================================================
create table if not exists public.nutrition_targets (
  user_id uuid primary key references auth.users (id) on delete cascade,
  calories int not null default 2200,
  protein_g int not null default 160,
  carbs_g int not null default 220,
  fat_g int not null default 70,
  updated_at timestamptz not null default now()
);
alter table public.nutrition_targets enable row level security;
drop policy if exists "own nutrition targets" on public.nutrition_targets;
create policy "own nutrition targets" on public.nutrition_targets
  for all to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());

-- ============================================================
-- 3. Meal entries (a planned/eaten item on a day + meal slot)
-- ============================================================
create table if not exists public.meal_entries (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users (id) on delete cascade,
  entry_date date not null default current_date,
  meal text not null default 'breakfast' check (meal in ('breakfast','lunch','dinner','snack')),
  recipe_id uuid references public.recipes (id) on delete set null,
  title text not null,
  calories int not null default 0,
  protein_g int not null default 0,
  carbs_g int not null default 0,
  fat_g int not null default 0,
  servings numeric(4,2) not null default 1,
  created_at timestamptz not null default now()
);
create index if not exists meal_entries_user_date_idx
  on public.meal_entries (user_id, entry_date);
alter table public.meal_entries enable row level security;
drop policy if exists "own meal entries" on public.meal_entries;
create policy "own meal entries" on public.meal_entries
  for all to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());

-- ============================================================
-- 4. Seed the recipe library
-- ============================================================
insert into public.recipes
  (slug, title, category, image_url, description, calories, protein_g, carbs_g, fat_g, servings, prep_minutes, tags, ingredients, steps)
values
('grilled-chicken-breast-with-brown-rice-1','Grilled chicken breast with brown rice','High-Protein','https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=800&q=80&auto=format&fit=crop','Grilled chicken breast with brown rice — a high-protein recipe with ~35g protein per serving.',392,35,45,4,1,20,array['high-protein','muscle'],array['chicken breast','brown rice','olive oil','seasoning','fresh herbs'],array['Prep and season the ingredients.','Cook the chicken breast.','Prepare the brown rice.','Plate, add herbs and serve.']),
('herb-roasted-chicken-breast-with-quinoa-2','Herb-roasted chicken breast with quinoa','High-Protein','https://images.unsplash.com/photo-1607532941433-304659e8198a?w=800&q=80&auto=format&fit=crop','Herb-roasted chicken breast with quinoa — a high-protein recipe with ~35g protein per serving.',398,35,39,4,1,20,array['high-protein','muscle'],array['chicken breast','quinoa','olive oil','seasoning','fresh herbs'],array['Prep and season the ingredients.','Cook the chicken breast.','Prepare the quinoa.','Plate, add herbs and serve.']),
('teriyaki-chicken-breast-with-sweet-potato-3','Teriyaki chicken breast with sweet potato','High-Protein','https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?w=800&q=80&auto=format&fit=crop','Teriyaki chicken breast with sweet potato — a high-protein recipe with ~35g protein per serving.',291,35,27,4,1,20,array['high-protein','muscle'],array['chicken breast','sweet potato','olive oil','seasoning','fresh herbs'],array['Prep and season the ingredients.','Cook the chicken breast.','Prepare the sweet potato.','Plate, add herbs and serve.']),
('garlic-butter-chicken-breast-with-roasted-veg-4','Garlic-butter chicken breast with roasted veg','High-Protein','https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=800&q=80&auto=format&fit=crop','Garlic-butter chicken breast with roasted veg — a high-protein recipe with ~35g protein per serving.',272,35,18,4,1,20,array['high-protein','muscle'],array['chicken breast','roasted veg','olive oil','seasoning','fresh herbs'],array['Prep and season the ingredients.','Cook the chicken breast.','Prepare the roasted veg.','Plate, add herbs and serve.']),
('cajun-lean-beef-with-brown-rice-5','Cajun lean beef with brown rice','High-Protein','https://images.unsplash.com/photo-1607532941433-304659e8198a?w=800&q=80&auto=format&fit=crop','Cajun lean beef with brown rice — a high-protein recipe with ~30g protein per serving.',444,30,45,12,1,20,array['high-protein','muscle'],array['lean beef','brown rice','olive oil','seasoning','fresh herbs'],array['Prep and season the ingredients.','Cook the lean beef.','Prepare the brown rice.','Plate, add herbs and serve.']),
('mediterranean-lean-beef-with-quinoa-6','Mediterranean lean beef with quinoa','High-Protein','https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?w=800&q=80&auto=format&fit=crop','Mediterranean lean beef with quinoa — a high-protein recipe with ~30g protein per serving.',450,30,39,12,1,20,array['high-protein','muscle'],array['lean beef','quinoa','olive oil','seasoning','fresh herbs'],array['Prep and season the ingredients.','Cook the lean beef.','Prepare the quinoa.','Plate, add herbs and serve.']),
('sesame-ginger-lean-beef-with-sweet-potato-7','Sesame-ginger lean beef with sweet potato','High-Protein','https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=800&q=80&auto=format&fit=crop','Sesame-ginger lean beef with sweet potato — a high-protein recipe with ~30g protein per serving.',343,30,27,12,1,20,array['high-protein','muscle'],array['lean beef','sweet potato','olive oil','seasoning','fresh herbs'],array['Prep and season the ingredients.','Cook the lean beef.','Prepare the sweet potato.','Plate, add herbs and serve.']),
('lemon-pepper-lean-beef-with-roasted-veg-8','Lemon-pepper lean beef with roasted veg','High-Protein','https://images.unsplash.com/photo-1607532941433-304659e8198a?w=800&q=80&auto=format&fit=crop','Lemon-pepper lean beef with roasted veg — a high-protein recipe with ~30g protein per serving.',324,30,18,12,1,20,array['high-protein','muscle'],array['lean beef','roasted veg','olive oil','seasoning','fresh herbs'],array['Prep and season the ingredients.','Cook the lean beef.','Prepare the roasted veg.','Plate, add herbs and serve.']),
('smoky-bbq-salmon-with-brown-rice-9','Smoky BBQ salmon with brown rice','High-Protein','https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?w=800&q=80&auto=format&fit=crop','Smoky BBQ salmon with brown rice — a high-protein recipe with ~28g protein per serving.',463,28,45,15,1,20,array['high-protein','muscle'],array['salmon','brown rice','olive oil','seasoning','fresh herbs'],array['Prep and season the ingredients.','Cook the salmon.','Prepare the brown rice.','Plate, add herbs and serve.']),
('peri-peri-salmon-with-quinoa-10','Peri-peri salmon with quinoa','High-Protein','https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=800&q=80&auto=format&fit=crop','Peri-peri salmon with quinoa — a high-protein recipe with ~28g protein per serving.',469,28,39,15,1,20,array['high-protein','muscle'],array['salmon','quinoa','olive oil','seasoning','fresh herbs'],array['Prep and season the ingredients.','Cook the salmon.','Prepare the quinoa.','Plate, add herbs and serve.']),
('miso-glazed-salmon-with-sweet-potato-11','Miso-glazed salmon with sweet potato','High-Protein','https://images.unsplash.com/photo-1607532941433-304659e8198a?w=800&q=80&auto=format&fit=crop','Miso-glazed salmon with sweet potato — a high-protein recipe with ~28g protein per serving.',362,28,27,15,1,20,array['high-protein','muscle'],array['salmon','sweet potato','olive oil','seasoning','fresh herbs'],array['Prep and season the ingredients.','Cook the salmon.','Prepare the sweet potato.','Plate, add herbs and serve.']),
('harissa-salmon-with-roasted-veg-12','Harissa salmon with roasted veg','High-Protein','https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?w=800&q=80&auto=format&fit=crop','Harissa salmon with roasted veg — a high-protein recipe with ~28g protein per serving.',343,28,18,15,1,20,array['high-protein','muscle'],array['salmon','roasted veg','olive oil','seasoning','fresh herbs'],array['Prep and season the ingredients.','Cook the salmon.','Prepare the roasted veg.','Plate, add herbs and serve.']),
('grilled-turkey-mince-with-brown-rice-13','Grilled turkey mince with brown rice','High-Protein','https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=800&q=80&auto=format&fit=crop','Grilled turkey mince with brown rice — a high-protein recipe with ~34g protein per serving.',424,34,45,8,1,20,array['high-protein','muscle'],array['turkey mince','brown rice','olive oil','seasoning','fresh herbs'],array['Prep and season the ingredients.','Cook the turkey mince.','Prepare the brown rice.','Plate, add herbs and serve.']),
('herb-roasted-turkey-mince-with-quinoa-14','Herb-roasted turkey mince with quinoa','High-Protein','https://images.unsplash.com/photo-1607532941433-304659e8198a?w=800&q=80&auto=format&fit=crop','Herb-roasted turkey mince with quinoa — a high-protein recipe with ~34g protein per serving.',430,34,39,8,1,20,array['high-protein','muscle'],array['turkey mince','quinoa','olive oil','seasoning','fresh herbs'],array['Prep and season the ingredients.','Cook the turkey mince.','Prepare the quinoa.','Plate, add herbs and serve.']),
('teriyaki-turkey-mince-with-sweet-potato-15','Teriyaki turkey mince with sweet potato','High-Protein','https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?w=800&q=80&auto=format&fit=crop','Teriyaki turkey mince with sweet potato — a high-protein recipe with ~34g protein per serving.',323,34,27,8,1,20,array['high-protein','muscle'],array['turkey mince','sweet potato','olive oil','seasoning','fresh herbs'],array['Prep and season the ingredients.','Cook the turkey mince.','Prepare the sweet potato.','Plate, add herbs and serve.']),
('garlic-butter-turkey-mince-with-roasted-veg-16','Garlic-butter turkey mince with roasted veg','High-Protein','https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=800&q=80&auto=format&fit=crop','Garlic-butter turkey mince with roasted veg — a high-protein recipe with ~34g protein per serving.',304,34,18,8,1,20,array['high-protein','muscle'],array['turkey mince','roasted veg','olive oil','seasoning','fresh herbs'],array['Prep and season the ingredients.','Cook the turkey mince.','Prepare the roasted veg.','Plate, add herbs and serve.']),
('cajun-prawns-with-brown-rice-17','Cajun prawns with brown rice','High-Protein','https://images.unsplash.com/photo-1607532941433-304659e8198a?w=800&q=80&auto=format&fit=crop','Cajun prawns with brown rice — a high-protein recipe with ~24g protein per serving.',338,24,46,2,1,20,array['high-protein','muscle'],array['prawns','brown rice','olive oil','seasoning','fresh herbs'],array['Prep and season the ingredients.','Cook the prawns.','Prepare the brown rice.','Plate, add herbs and serve.']),
('mediterranean-prawns-with-quinoa-18','Mediterranean prawns with quinoa','High-Protein','https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?w=800&q=80&auto=format&fit=crop','Mediterranean prawns with quinoa — a high-protein recipe with ~24g protein per serving.',344,24,40,2,1,20,array['high-protein','muscle'],array['prawns','quinoa','olive oil','seasoning','fresh herbs'],array['Prep and season the ingredients.','Cook the prawns.','Prepare the quinoa.','Plate, add herbs and serve.']),
('sesame-ginger-prawns-with-sweet-potato-19','Sesame-ginger prawns with sweet potato','High-Protein','https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=800&q=80&auto=format&fit=crop','Sesame-ginger prawns with sweet potato — a high-protein recipe with ~24g protein per serving.',237,24,28,2,1,20,array['high-protein','muscle'],array['prawns','sweet potato','olive oil','seasoning','fresh herbs'],array['Prep and season the ingredients.','Cook the prawns.','Prepare the sweet potato.','Plate, add herbs and serve.']),
('lemon-pepper-prawns-with-roasted-veg-20','Lemon-pepper prawns with roasted veg','High-Protein','https://images.unsplash.com/photo-1607532941433-304659e8198a?w=800&q=80&auto=format&fit=crop','Lemon-pepper prawns with roasted veg — a high-protein recipe with ~24g protein per serving.',218,24,19,2,1,20,array['high-protein','muscle'],array['prawns','roasted veg','olive oil','seasoning','fresh herbs'],array['Prep and season the ingredients.','Cook the prawns.','Prepare the roasted veg.','Plate, add herbs and serve.']),
('smoky-bbq-cottage-cheese-with-brown-rice-21','Smoky BBQ cottage cheese with brown rice','High-Protein','https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?w=800&q=80&auto=format&fit=crop','Smoky BBQ cottage cheese with brown rice — a high-protein recipe with ~24g protein per serving.',379,24,51,5,1,20,array['high-protein','muscle'],array['cottage cheese','brown rice','olive oil','seasoning','fresh herbs'],array['Prep and season the ingredients.','Cook the cottage cheese.','Prepare the brown rice.','Plate, add herbs and serve.']),
('peri-peri-cottage-cheese-with-quinoa-22','Peri-peri cottage cheese with quinoa','High-Protein','https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=800&q=80&auto=format&fit=crop','Peri-peri cottage cheese with quinoa — a high-protein recipe with ~24g protein per serving.',385,24,45,5,1,20,array['high-protein','muscle'],array['cottage cheese','quinoa','olive oil','seasoning','fresh herbs'],array['Prep and season the ingredients.','Cook the cottage cheese.','Prepare the quinoa.','Plate, add herbs and serve.']),
('miso-glazed-cottage-cheese-with-sweet-potato-23','Miso-glazed cottage cheese with sweet potato','High-Protein','https://images.unsplash.com/photo-1607532941433-304659e8198a?w=800&q=80&auto=format&fit=crop','Miso-glazed cottage cheese with sweet potato — a high-protein recipe with ~24g protein per serving.',278,24,33,5,1,20,array['high-protein','muscle'],array['cottage cheese','sweet potato','olive oil','seasoning','fresh herbs'],array['Prep and season the ingredients.','Cook the cottage cheese.','Prepare the sweet potato.','Plate, add herbs and serve.']),
('harissa-cottage-cheese-with-roasted-veg-24','Harissa cottage cheese with roasted veg','High-Protein','https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?w=800&q=80&auto=format&fit=crop','Harissa cottage cheese with roasted veg — a high-protein recipe with ~24g protein per serving.',259,24,24,5,1,20,array['high-protein','muscle'],array['cottage cheese','roasted veg','olive oil','seasoning','fresh herbs'],array['Prep and season the ingredients.','Cook the cottage cheese.','Prepare the roasted veg.','Plate, add herbs and serve.']),
('grilled-grilled-chicken-with-mixed-greens-25','Grilled grilled chicken with mixed greens','Low-Carb','https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800&q=80&auto=format&fit=crop','Grilled grilled chicken with mixed greens — a low-carb recipe with ~32g protein per serving.',203,32,8,5,1,20,array['low-carb','cut'],array['grilled chicken','mixed greens','olive oil','seasoning','fresh herbs'],array['Prep and season the ingredients.','Cook the grilled chicken.','Prepare the mixed greens.','Plate, add herbs and serve.']),
('herb-roasted-grilled-chicken-with-roasted-veg-26','Herb-roasted grilled chicken with roasted veg','Low-Carb','https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=800&q=80&auto=format&fit=crop','Herb-roasted grilled chicken with roasted veg — a low-carb recipe with ~32g protein per serving.',269,32,20,5,1,20,array['low-carb','cut'],array['grilled chicken','roasted veg','olive oil','seasoning','fresh herbs'],array['Prep and season the ingredients.','Cook the grilled chicken.','Prepare the roasted veg.','Plate, add herbs and serve.']),
('teriyaki-grilled-chicken-27','Teriyaki grilled chicken','Low-Carb','https://images.unsplash.com/photo-1490645935967-10de6ba17061?w=800&q=80&auto=format&fit=crop','Teriyaki grilled chicken — a low-carb recipe with ~32g protein per serving.',173,32,2,5,1,20,array['low-carb','cut'],array['grilled chicken','olive oil','seasoning','fresh herbs'],array['Prep and season the ingredients.','Cook the grilled chicken.','Assemble.','Plate, add herbs and serve.']),
('garlic-butter-salmon-with-mixed-greens-28','Garlic-butter salmon with mixed greens','Low-Carb','https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800&q=80&auto=format&fit=crop','Garlic-butter salmon with mixed greens — a low-carb recipe with ~28g protein per serving.',277,28,6,15,1,20,array['low-carb','cut'],array['salmon','mixed greens','olive oil','seasoning','fresh herbs'],array['Prep and season the ingredients.','Cook the salmon.','Prepare the mixed greens.','Plate, add herbs and serve.']),
('cajun-salmon-with-roasted-veg-29','Cajun salmon with roasted veg','Low-Carb','https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=800&q=80&auto=format&fit=crop','Cajun salmon with roasted veg — a low-carb recipe with ~28g protein per serving.',343,28,18,15,1,20,array['low-carb','cut'],array['salmon','roasted veg','olive oil','seasoning','fresh herbs'],array['Prep and season the ingredients.','Cook the salmon.','Prepare the roasted veg.','Plate, add herbs and serve.']),
('mediterranean-salmon-30','Mediterranean salmon','Low-Carb','https://images.unsplash.com/photo-1490645935967-10de6ba17061?w=800&q=80&auto=format&fit=crop','Mediterranean salmon — a low-carb recipe with ~28g protein per serving.',247,28,0,15,1,20,array['low-carb','cut'],array['salmon','olive oil','seasoning','fresh herbs'],array['Prep and season the ingredients.','Cook the salmon.','Assemble.','Plate, add herbs and serve.']),
('sesame-ginger-white-fish-with-mixed-greens-31','Sesame-ginger white fish with mixed greens','Low-Carb','https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800&q=80&auto=format&fit=crop','Sesame-ginger white fish with mixed greens — a low-carb recipe with ~26g protein per serving.',161,26,6,3,1,20,array['low-carb','cut'],array['white fish','mixed greens','olive oil','seasoning','fresh herbs'],array['Prep and season the ingredients.','Cook the white fish.','Prepare the mixed greens.','Plate, add herbs and serve.']),
('lemon-pepper-white-fish-with-roasted-veg-32','Lemon-pepper white fish with roasted veg','Low-Carb','https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=800&q=80&auto=format&fit=crop','Lemon-pepper white fish with roasted veg — a low-carb recipe with ~26g protein per serving.',227,26,18,3,1,20,array['low-carb','cut'],array['white fish','roasted veg','olive oil','seasoning','fresh herbs'],array['Prep and season the ingredients.','Cook the white fish.','Prepare the roasted veg.','Plate, add herbs and serve.']),
('smoky-bbq-white-fish-33','Smoky BBQ white fish','Low-Carb','https://images.unsplash.com/photo-1490645935967-10de6ba17061?w=800&q=80&auto=format&fit=crop','Smoky BBQ white fish — a low-carb recipe with ~26g protein per serving.',131,26,0,3,1,20,array['low-carb','cut'],array['white fish','olive oil','seasoning','fresh herbs'],array['Prep and season the ingredients.','Cook the white fish.','Assemble.','Plate, add herbs and serve.']),
('peri-peri-eggs-with-mixed-greens-34','Peri-peri eggs with mixed greens','Low-Carb','https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800&q=80&auto=format&fit=crop','Peri-peri eggs with mixed greens — a low-carb recipe with ~18g protein per serving.',245,18,8,15,1,20,array['low-carb','cut'],array['eggs','mixed greens','olive oil','seasoning','fresh herbs'],array['Prep and season the ingredients.','Cook the eggs.','Prepare the mixed greens.','Plate, add herbs and serve.']),
('miso-glazed-eggs-with-roasted-veg-35','Miso-glazed eggs with roasted veg','Low-Carb','https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=800&q=80&auto=format&fit=crop','Miso-glazed eggs with roasted veg — a low-carb recipe with ~18g protein per serving.',311,18,20,15,1,20,array['low-carb','cut'],array['eggs','roasted veg','olive oil','seasoning','fresh herbs'],array['Prep and season the ingredients.','Cook the eggs.','Prepare the roasted veg.','Plate, add herbs and serve.']),
('harissa-eggs-36','Harissa eggs','Low-Carb','https://images.unsplash.com/photo-1490645935967-10de6ba17061?w=800&q=80&auto=format&fit=crop','Harissa eggs — a low-carb recipe with ~18g protein per serving.',215,18,2,15,1,20,array['low-carb','cut'],array['eggs','olive oil','seasoning','fresh herbs'],array['Prep and season the ingredients.','Cook the eggs.','Assemble.','Plate, add herbs and serve.']),
('grilled-lean-beef-with-mixed-greens-37','Grilled lean beef with mixed greens','Low-Carb','https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800&q=80&auto=format&fit=crop','Grilled lean beef with mixed greens — a low-carb recipe with ~30g protein per serving.',258,30,6,12,1,20,array['low-carb','cut'],array['lean beef','mixed greens','olive oil','seasoning','fresh herbs'],array['Prep and season the ingredients.','Cook the lean beef.','Prepare the mixed greens.','Plate, add herbs and serve.']),
('herb-roasted-lean-beef-with-roasted-veg-38','Herb-roasted lean beef with roasted veg','Low-Carb','https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=800&q=80&auto=format&fit=crop','Herb-roasted lean beef with roasted veg — a low-carb recipe with ~30g protein per serving.',324,30,18,12,1,20,array['low-carb','cut'],array['lean beef','roasted veg','olive oil','seasoning','fresh herbs'],array['Prep and season the ingredients.','Cook the lean beef.','Prepare the roasted veg.','Plate, add herbs and serve.']),
('teriyaki-lean-beef-39','Teriyaki lean beef','Low-Carb','https://images.unsplash.com/photo-1490645935967-10de6ba17061?w=800&q=80&auto=format&fit=crop','Teriyaki lean beef — a low-carb recipe with ~30g protein per serving.',228,30,0,12,1,20,array['low-carb','cut'],array['lean beef','olive oil','seasoning','fresh herbs'],array['Prep and season the ingredients.','Cook the lean beef.','Assemble.','Plate, add herbs and serve.']),
('grilled-tofu-with-brown-rice-40','Grilled tofu with brown rice','Vegan','https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800&q=80&auto=format&fit=crop','Grilled tofu with brown rice — a vegan recipe with ~18g protein per serving.',385,18,49,9,1,20,array['vegan','plant-based'],array['tofu','brown rice','olive oil','seasoning','fresh herbs'],array['Prep and season the ingredients.','Cook the tofu.','Prepare the brown rice.','Plate, add herbs and serve.']),
('herb-roasted-tofu-with-quinoa-41','Herb-roasted tofu with quinoa','Vegan','https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=800&q=80&auto=format&fit=crop','Herb-roasted tofu with quinoa — a vegan recipe with ~18g protein per serving.',391,18,43,9,1,20,array['vegan','plant-based'],array['tofu','quinoa','olive oil','seasoning','fresh herbs'],array['Prep and season the ingredients.','Cook the tofu.','Prepare the quinoa.','Plate, add herbs and serve.']),
('teriyaki-tofu-with-roasted-veg-42','Teriyaki tofu with roasted veg','Vegan','https://images.unsplash.com/photo-1543339308-43e59d6b73a6?w=800&q=80&auto=format&fit=crop','Teriyaki tofu with roasted veg — a vegan recipe with ~18g protein per serving.',265,18,22,9,1,20,array['vegan','plant-based'],array['tofu','roasted veg','olive oil','seasoning','fresh herbs'],array['Prep and season the ingredients.','Cook the tofu.','Prepare the roasted veg.','Plate, add herbs and serve.']),
('garlic-butter-tofu-with-sweet-potato-43','Garlic-butter tofu with sweet potato','Vegan','https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800&q=80&auto=format&fit=crop','Garlic-butter tofu with sweet potato — a vegan recipe with ~18g protein per serving.',284,18,31,9,1,20,array['vegan','plant-based'],array['tofu','sweet potato','olive oil','seasoning','fresh herbs'],array['Prep and season the ingredients.','Cook the tofu.','Prepare the sweet potato.','Plate, add herbs and serve.']),
('cajun-tempeh-with-brown-rice-44','Cajun tempeh with brown rice','Vegan','https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=800&q=80&auto=format&fit=crop','Cajun tempeh with brown rice — a vegan recipe with ~20g protein per serving.',427,20,53,11,1,20,array['vegan','plant-based'],array['tempeh','brown rice','olive oil','seasoning','fresh herbs'],array['Prep and season the ingredients.','Cook the tempeh.','Prepare the brown rice.','Plate, add herbs and serve.']),
('mediterranean-tempeh-with-quinoa-45','Mediterranean tempeh with quinoa','Vegan','https://images.unsplash.com/photo-1543339308-43e59d6b73a6?w=800&q=80&auto=format&fit=crop','Mediterranean tempeh with quinoa — a vegan recipe with ~20g protein per serving.',433,20,47,11,1,20,array['vegan','plant-based'],array['tempeh','quinoa','olive oil','seasoning','fresh herbs'],array['Prep and season the ingredients.','Cook the tempeh.','Prepare the quinoa.','Plate, add herbs and serve.']),
('sesame-ginger-tempeh-with-roasted-veg-46','Sesame-ginger tempeh with roasted veg','Vegan','https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800&q=80&auto=format&fit=crop','Sesame-ginger tempeh with roasted veg — a vegan recipe with ~20g protein per serving.',307,20,26,11,1,20,array['vegan','plant-based'],array['tempeh','roasted veg','olive oil','seasoning','fresh herbs'],array['Prep and season the ingredients.','Cook the tempeh.','Prepare the roasted veg.','Plate, add herbs and serve.']),
('lemon-pepper-tempeh-with-sweet-potato-47','Lemon-pepper tempeh with sweet potato','Vegan','https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=800&q=80&auto=format&fit=crop','Lemon-pepper tempeh with sweet potato — a vegan recipe with ~20g protein per serving.',326,20,35,11,1,20,array['vegan','plant-based'],array['tempeh','sweet potato','olive oil','seasoning','fresh herbs'],array['Prep and season the ingredients.','Cook the tempeh.','Prepare the sweet potato.','Plate, add herbs and serve.']),
('smoky-bbq-chickpeas-with-brown-rice-48','Smoky BBQ chickpeas with brown rice','Vegan','https://images.unsplash.com/photo-1543339308-43e59d6b73a6?w=800&q=80&auto=format&fit=crop','Smoky BBQ chickpeas with brown rice — a vegan recipe with ~14g protein per serving.',486,14,85,6,1,20,array['vegan','plant-based'],array['chickpeas','brown rice','olive oil','seasoning','fresh herbs'],array['Prep and season the ingredients.','Cook the chickpeas.','Prepare the brown rice.','Plate, add herbs and serve.']),
('peri-peri-chickpeas-with-quinoa-49','Peri-peri chickpeas with quinoa','Vegan','https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800&q=80&auto=format&fit=crop','Peri-peri chickpeas with quinoa — a vegan recipe with ~14g protein per serving.',492,14,79,6,1,20,array['vegan','plant-based'],array['chickpeas','quinoa','olive oil','seasoning','fresh herbs'],array['Prep and season the ingredients.','Cook the chickpeas.','Prepare the quinoa.','Plate, add herbs and serve.']),
('miso-glazed-chickpeas-with-roasted-veg-50','Miso-glazed chickpeas with roasted veg','Vegan','https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=800&q=80&auto=format&fit=crop','Miso-glazed chickpeas with roasted veg — a vegan recipe with ~14g protein per serving.',366,14,58,6,1,20,array['vegan','plant-based'],array['chickpeas','roasted veg','olive oil','seasoning','fresh herbs'],array['Prep and season the ingredients.','Cook the chickpeas.','Prepare the roasted veg.','Plate, add herbs and serve.']),
('harissa-chickpeas-with-sweet-potato-51','Harissa chickpeas with sweet potato','Vegan','https://images.unsplash.com/photo-1543339308-43e59d6b73a6?w=800&q=80&auto=format&fit=crop','Harissa chickpeas with sweet potato — a vegan recipe with ~14g protein per serving.',385,14,67,6,1,20,array['vegan','plant-based'],array['chickpeas','sweet potato','olive oil','seasoning','fresh herbs'],array['Prep and season the ingredients.','Cook the chickpeas.','Prepare the sweet potato.','Plate, add herbs and serve.']),
('grilled-black-beans-with-brown-rice-52','Grilled black beans with brown rice','Vegan','https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800&q=80&auto=format&fit=crop','Grilled black beans with brown rice — a vegan recipe with ~15g protein per serving.',458,15,86,2,1,20,array['vegan','plant-based'],array['black beans','brown rice','olive oil','seasoning','fresh herbs'],array['Prep and season the ingredients.','Cook the black beans.','Prepare the brown rice.','Plate, add herbs and serve.']),
('herb-roasted-black-beans-with-quinoa-53','Herb-roasted black beans with quinoa','Vegan','https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=800&q=80&auto=format&fit=crop','Herb-roasted black beans with quinoa — a vegan recipe with ~15g protein per serving.',464,15,80,2,1,20,array['vegan','plant-based'],array['black beans','quinoa','olive oil','seasoning','fresh herbs'],array['Prep and season the ingredients.','Cook the black beans.','Prepare the quinoa.','Plate, add herbs and serve.']),
('teriyaki-black-beans-with-roasted-veg-54','Teriyaki black beans with roasted veg','Vegan','https://images.unsplash.com/photo-1543339308-43e59d6b73a6?w=800&q=80&auto=format&fit=crop','Teriyaki black beans with roasted veg — a vegan recipe with ~15g protein per serving.',338,15,59,2,1,20,array['vegan','plant-based'],array['black beans','roasted veg','olive oil','seasoning','fresh herbs'],array['Prep and season the ingredients.','Cook the black beans.','Prepare the roasted veg.','Plate, add herbs and serve.']),
('garlic-butter-black-beans-with-sweet-potato-55','Garlic-butter black beans with sweet potato','Vegan','https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800&q=80&auto=format&fit=crop','Garlic-butter black beans with sweet potato — a vegan recipe with ~15g protein per serving.',357,15,68,2,1,20,array['vegan','plant-based'],array['black beans','sweet potato','olive oil','seasoning','fresh herbs'],array['Prep and season the ingredients.','Cook the black beans.','Prepare the sweet potato.','Plate, add herbs and serve.']),
('cajun-lentils-with-brown-rice-56','Cajun lentils with brown rice','Vegan','https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=800&q=80&auto=format&fit=crop','Cajun lentils with brown rice — a vegan recipe with ~18g protein per serving.',457,18,85,1,1,20,array['vegan','plant-based'],array['lentils','brown rice','olive oil','seasoning','fresh herbs'],array['Prep and season the ingredients.','Cook the lentils.','Prepare the brown rice.','Plate, add herbs and serve.']),
('mediterranean-lentils-with-quinoa-57','Mediterranean lentils with quinoa','Vegan','https://images.unsplash.com/photo-1543339308-43e59d6b73a6?w=800&q=80&auto=format&fit=crop','Mediterranean lentils with quinoa — a vegan recipe with ~18g protein per serving.',463,18,79,1,1,20,array['vegan','plant-based'],array['lentils','quinoa','olive oil','seasoning','fresh herbs'],array['Prep and season the ingredients.','Cook the lentils.','Prepare the quinoa.','Plate, add herbs and serve.']),
('sesame-ginger-lentils-with-roasted-veg-58','Sesame-ginger lentils with roasted veg','Vegan','https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800&q=80&auto=format&fit=crop','Sesame-ginger lentils with roasted veg — a vegan recipe with ~18g protein per serving.',337,18,58,1,1,20,array['vegan','plant-based'],array['lentils','roasted veg','olive oil','seasoning','fresh herbs'],array['Prep and season the ingredients.','Cook the lentils.','Prepare the roasted veg.','Plate, add herbs and serve.']),
('lemon-pepper-lentils-with-sweet-potato-59','Lemon-pepper lentils with sweet potato','Vegan','https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=800&q=80&auto=format&fit=crop','Lemon-pepper lentils with sweet potato — a vegan recipe with ~18g protein per serving.',356,18,67,1,1,20,array['vegan','plant-based'],array['lentils','sweet potato','olive oil','seasoning','fresh herbs'],array['Prep and season the ingredients.','Cook the lentils.','Prepare the sweet potato.','Plate, add herbs and serve.']),
('grilled-eggs-with-oats-60','Grilled eggs with oats','Vegetarian','https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?w=800&q=80&auto=format&fit=crop','Grilled eggs with oats — a vegetarian recipe with ~18g protein per serving.',365,18,29,15,1,20,array['vegetarian'],array['eggs','oats','olive oil','seasoning','fresh herbs'],array['Prep and season the ingredients.','Cook the eggs.','Prepare the oats.','Plate, add herbs and serve.']),
('herb-roasted-eggs-with-quinoa-61','Herb-roasted eggs with quinoa','Vegetarian','https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800&q=80&auto=format&fit=crop','Herb-roasted eggs with quinoa — a vegetarian recipe with ~18g protein per serving.',437,18,41,15,1,20,array['vegetarian'],array['eggs','quinoa','olive oil','seasoning','fresh herbs'],array['Prep and season the ingredients.','Cook the eggs.','Prepare the quinoa.','Plate, add herbs and serve.']),
('teriyaki-eggs-with-roasted-veg-62','Teriyaki eggs with roasted veg','Vegetarian','https://images.unsplash.com/photo-1476224203421-9ac39bcb3327?w=800&q=80&auto=format&fit=crop','Teriyaki eggs with roasted veg — a vegetarian recipe with ~18g protein per serving.',311,18,20,15,1,20,array['vegetarian'],array['eggs','roasted veg','olive oil','seasoning','fresh herbs'],array['Prep and season the ingredients.','Cook the eggs.','Prepare the roasted veg.','Plate, add herbs and serve.']),
('garlic-butter-eggs-with-berries-63','Garlic-butter eggs with berries','Vegetarian','https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?w=800&q=80&auto=format&fit=crop','Garlic-butter eggs with berries — a vegetarian recipe with ~18g protein per serving.',285,18,19,15,1,20,array['vegetarian'],array['eggs','berries','olive oil','seasoning','fresh herbs'],array['Prep and season the ingredients.','Cook the eggs.','Prepare the berries.','Plate, add herbs and serve.']),
('cajun-greek-yogurt-with-oats-64','Cajun greek yogurt with oats','Vegetarian','https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800&q=80&auto=format&fit=crop','Cajun greek yogurt with oats — a vegetarian recipe with ~17g protein per serving.',286,17,35,4,1,20,array['vegetarian'],array['greek yogurt','oats','olive oil','seasoning','fresh herbs'],array['Prep and season the ingredients.','Cook the greek yogurt.','Prepare the oats.','Plate, add herbs and serve.']),
('mediterranean-greek-yogurt-with-quinoa-65','Mediterranean greek yogurt with quinoa','Vegetarian','https://images.unsplash.com/photo-1476224203421-9ac39bcb3327?w=800&q=80&auto=format&fit=crop','Mediterranean greek yogurt with quinoa — a vegetarian recipe with ~17g protein per serving.',358,17,47,4,1,20,array['vegetarian'],array['greek yogurt','quinoa','olive oil','seasoning','fresh herbs'],array['Prep and season the ingredients.','Cook the greek yogurt.','Prepare the quinoa.','Plate, add herbs and serve.']),
('sesame-ginger-greek-yogurt-with-roasted-veg-66','Sesame-ginger greek yogurt with roasted veg','Vegetarian','https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?w=800&q=80&auto=format&fit=crop','Sesame-ginger greek yogurt with roasted veg — a vegetarian recipe with ~17g protein per serving.',232,17,26,4,1,20,array['vegetarian'],array['greek yogurt','roasted veg','olive oil','seasoning','fresh herbs'],array['Prep and season the ingredients.','Cook the greek yogurt.','Prepare the roasted veg.','Plate, add herbs and serve.']),
('lemon-pepper-greek-yogurt-with-berries-67','Lemon-pepper greek yogurt with berries','Vegetarian','https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800&q=80&auto=format&fit=crop','Lemon-pepper greek yogurt with berries — a vegetarian recipe with ~17g protein per serving.',206,17,25,4,1,20,array['vegetarian'],array['greek yogurt','berries','olive oil','seasoning','fresh herbs'],array['Prep and season the ingredients.','Cook the greek yogurt.','Prepare the berries.','Plate, add herbs and serve.']),
('smoky-bbq-chickpeas-with-oats-68','Smoky BBQ chickpeas with oats','Vegetarian','https://images.unsplash.com/photo-1476224203421-9ac39bcb3327?w=800&q=80&auto=format&fit=crop','Smoky BBQ chickpeas with oats — a vegetarian recipe with ~14g protein per serving.',420,14,67,6,1,20,array['vegetarian'],array['chickpeas','oats','olive oil','seasoning','fresh herbs'],array['Prep and season the ingredients.','Cook the chickpeas.','Prepare the oats.','Plate, add herbs and serve.']),
('peri-peri-chickpeas-with-quinoa-69','Peri-peri chickpeas with quinoa','Vegetarian','https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?w=800&q=80&auto=format&fit=crop','Peri-peri chickpeas with quinoa — a vegetarian recipe with ~14g protein per serving.',492,14,79,6,1,20,array['vegetarian'],array['chickpeas','quinoa','olive oil','seasoning','fresh herbs'],array['Prep and season the ingredients.','Cook the chickpeas.','Prepare the quinoa.','Plate, add herbs and serve.']),
('miso-glazed-chickpeas-with-roasted-veg-70','Miso-glazed chickpeas with roasted veg','Vegetarian','https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800&q=80&auto=format&fit=crop','Miso-glazed chickpeas with roasted veg — a vegetarian recipe with ~14g protein per serving.',366,14,58,6,1,20,array['vegetarian'],array['chickpeas','roasted veg','olive oil','seasoning','fresh herbs'],array['Prep and season the ingredients.','Cook the chickpeas.','Prepare the roasted veg.','Plate, add herbs and serve.']),
('harissa-chickpeas-with-berries-71','Harissa chickpeas with berries','Vegetarian','https://images.unsplash.com/photo-1476224203421-9ac39bcb3327?w=800&q=80&auto=format&fit=crop','Harissa chickpeas with berries — a vegetarian recipe with ~14g protein per serving.',340,14,57,6,1,20,array['vegetarian'],array['chickpeas','berries','olive oil','seasoning','fresh herbs'],array['Prep and season the ingredients.','Cook the chickpeas.','Prepare the berries.','Plate, add herbs and serve.']),
('grilled-tofu-with-oats-72','Grilled tofu with oats','Vegetarian','https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?w=800&q=80&auto=format&fit=crop','Grilled tofu with oats — a vegetarian recipe with ~18g protein per serving.',319,18,31,9,1,20,array['vegetarian'],array['tofu','oats','olive oil','seasoning','fresh herbs'],array['Prep and season the ingredients.','Cook the tofu.','Prepare the oats.','Plate, add herbs and serve.']),
('herb-roasted-tofu-with-quinoa-73','Herb-roasted tofu with quinoa','Vegetarian','https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800&q=80&auto=format&fit=crop','Herb-roasted tofu with quinoa — a vegetarian recipe with ~18g protein per serving.',391,18,43,9,1,20,array['vegetarian'],array['tofu','quinoa','olive oil','seasoning','fresh herbs'],array['Prep and season the ingredients.','Cook the tofu.','Prepare the quinoa.','Plate, add herbs and serve.']),
('teriyaki-tofu-with-roasted-veg-74','Teriyaki tofu with roasted veg','Vegetarian','https://images.unsplash.com/photo-1476224203421-9ac39bcb3327?w=800&q=80&auto=format&fit=crop','Teriyaki tofu with roasted veg — a vegetarian recipe with ~18g protein per serving.',265,18,22,9,1,20,array['vegetarian'],array['tofu','roasted veg','olive oil','seasoning','fresh herbs'],array['Prep and season the ingredients.','Cook the tofu.','Prepare the roasted veg.','Plate, add herbs and serve.']),
('garlic-butter-tofu-with-berries-75','Garlic-butter tofu with berries','Vegetarian','https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?w=800&q=80&auto=format&fit=crop','Garlic-butter tofu with berries — a vegetarian recipe with ~18g protein per serving.',239,18,21,9,1,20,array['vegetarian'],array['tofu','berries','olive oil','seasoning','fresh herbs'],array['Prep and season the ingredients.','Cook the tofu.','Prepare the berries.','Plate, add herbs and serve.']),
('cajun-cottage-cheese-with-oats-76','Cajun cottage cheese with oats','Vegetarian','https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800&q=80&auto=format&fit=crop','Cajun cottage cheese with oats — a vegetarian recipe with ~24g protein per serving.',313,24,33,5,1,20,array['vegetarian'],array['cottage cheese','oats','olive oil','seasoning','fresh herbs'],array['Prep and season the ingredients.','Cook the cottage cheese.','Prepare the oats.','Plate, add herbs and serve.']),
('mediterranean-cottage-cheese-with-quinoa-77','Mediterranean cottage cheese with quinoa','Vegetarian','https://images.unsplash.com/photo-1476224203421-9ac39bcb3327?w=800&q=80&auto=format&fit=crop','Mediterranean cottage cheese with quinoa — a vegetarian recipe with ~24g protein per serving.',385,24,45,5,1,20,array['vegetarian'],array['cottage cheese','quinoa','olive oil','seasoning','fresh herbs'],array['Prep and season the ingredients.','Cook the cottage cheese.','Prepare the quinoa.','Plate, add herbs and serve.']),
('sesame-ginger-cottage-cheese-with-roasted-veg-78','Sesame-ginger cottage cheese with roasted veg','Vegetarian','https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?w=800&q=80&auto=format&fit=crop','Sesame-ginger cottage cheese with roasted veg — a vegetarian recipe with ~24g protein per serving.',259,24,24,5,1,20,array['vegetarian'],array['cottage cheese','roasted veg','olive oil','seasoning','fresh herbs'],array['Prep and season the ingredients.','Cook the cottage cheese.','Prepare the roasted veg.','Plate, add herbs and serve.']),
('lemon-pepper-cottage-cheese-with-berries-79','Lemon-pepper cottage cheese with berries','Vegetarian','https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800&q=80&auto=format&fit=crop','Lemon-pepper cottage cheese with berries — a vegetarian recipe with ~24g protein per serving.',233,24,23,5,1,20,array['vegetarian'],array['cottage cheese','berries','olive oil','seasoning','fresh herbs'],array['Prep and season the ingredients.','Cook the cottage cheese.','Prepare the berries.','Plate, add herbs and serve.']),
('grilled-grilled-chicken-with-brown-rice-80','Grilled grilled chicken with brown rice','Bowls','https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=800&q=80&auto=format&fit=crop','Grilled grilled chicken with brown rice — a bowls recipe with ~32g protein per serving.',389,32,47,5,1,20,array['bowl','balanced'],array['grilled chicken','brown rice','olive oil','seasoning','fresh herbs'],array['Prep and season the ingredients.','Cook the grilled chicken.','Prepare the brown rice.','Plate, add herbs and serve.']),
('herb-roasted-grilled-chicken-with-quinoa-81','Herb-roasted grilled chicken with quinoa','Bowls','https://images.unsplash.com/photo-1543339308-43e59d6b73a6?w=800&q=80&auto=format&fit=crop','Herb-roasted grilled chicken with quinoa — a bowls recipe with ~32g protein per serving.',395,32,41,5,1,20,array['bowl','balanced'],array['grilled chicken','quinoa','olive oil','seasoning','fresh herbs'],array['Prep and season the ingredients.','Cook the grilled chicken.','Prepare the quinoa.','Plate, add herbs and serve.']),
('teriyaki-grilled-chicken-with-sweet-potato-82','Teriyaki grilled chicken with sweet potato','Bowls','https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800&q=80&auto=format&fit=crop','Teriyaki grilled chicken with sweet potato — a bowls recipe with ~32g protein per serving.',288,32,29,5,1,20,array['bowl','balanced'],array['grilled chicken','sweet potato','olive oil','seasoning','fresh herbs'],array['Prep and season the ingredients.','Cook the grilled chicken.','Prepare the sweet potato.','Plate, add herbs and serve.']),
('garlic-butter-tofu-with-brown-rice-83','Garlic-butter tofu with brown rice','Bowls','https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=800&q=80&auto=format&fit=crop','Garlic-butter tofu with brown rice — a bowls recipe with ~18g protein per serving.',385,18,49,9,1,20,array['bowl','balanced'],array['tofu','brown rice','olive oil','seasoning','fresh herbs'],array['Prep and season the ingredients.','Cook the tofu.','Prepare the brown rice.','Plate, add herbs and serve.']),
('cajun-tofu-with-quinoa-84','Cajun tofu with quinoa','Bowls','https://images.unsplash.com/photo-1543339308-43e59d6b73a6?w=800&q=80&auto=format&fit=crop','Cajun tofu with quinoa — a bowls recipe with ~18g protein per serving.',391,18,43,9,1,20,array['bowl','balanced'],array['tofu','quinoa','olive oil','seasoning','fresh herbs'],array['Prep and season the ingredients.','Cook the tofu.','Prepare the quinoa.','Plate, add herbs and serve.']),
('mediterranean-tofu-with-sweet-potato-85','Mediterranean tofu with sweet potato','Bowls','https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800&q=80&auto=format&fit=crop','Mediterranean tofu with sweet potato — a bowls recipe with ~18g protein per serving.',284,18,31,9,1,20,array['bowl','balanced'],array['tofu','sweet potato','olive oil','seasoning','fresh herbs'],array['Prep and season the ingredients.','Cook the tofu.','Prepare the sweet potato.','Plate, add herbs and serve.']),
('sesame-ginger-salmon-with-brown-rice-86','Sesame-ginger salmon with brown rice','Bowls','https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=800&q=80&auto=format&fit=crop','Sesame-ginger salmon with brown rice — a bowls recipe with ~28g protein per serving.',463,28,45,15,1,20,array['bowl','balanced'],array['salmon','brown rice','olive oil','seasoning','fresh herbs'],array['Prep and season the ingredients.','Cook the salmon.','Prepare the brown rice.','Plate, add herbs and serve.']),
('lemon-pepper-salmon-with-quinoa-87','Lemon-pepper salmon with quinoa','Bowls','https://images.unsplash.com/photo-1543339308-43e59d6b73a6?w=800&q=80&auto=format&fit=crop','Lemon-pepper salmon with quinoa — a bowls recipe with ~28g protein per serving.',469,28,39,15,1,20,array['bowl','balanced'],array['salmon','quinoa','olive oil','seasoning','fresh herbs'],array['Prep and season the ingredients.','Cook the salmon.','Prepare the quinoa.','Plate, add herbs and serve.']),
('smoky-bbq-salmon-with-sweet-potato-88','Smoky BBQ salmon with sweet potato','Bowls','https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800&q=80&auto=format&fit=crop','Smoky BBQ salmon with sweet potato — a bowls recipe with ~28g protein per serving.',362,28,27,15,1,20,array['bowl','balanced'],array['salmon','sweet potato','olive oil','seasoning','fresh herbs'],array['Prep and season the ingredients.','Cook the salmon.','Prepare the sweet potato.','Plate, add herbs and serve.']),
('peri-peri-chickpeas-with-brown-rice-89','Peri-peri chickpeas with brown rice','Bowls','https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=800&q=80&auto=format&fit=crop','Peri-peri chickpeas with brown rice — a bowls recipe with ~14g protein per serving.',486,14,85,6,1,20,array['bowl','balanced'],array['chickpeas','brown rice','olive oil','seasoning','fresh herbs'],array['Prep and season the ingredients.','Cook the chickpeas.','Prepare the brown rice.','Plate, add herbs and serve.']),
('miso-glazed-chickpeas-with-quinoa-90','Miso-glazed chickpeas with quinoa','Bowls','https://images.unsplash.com/photo-1543339308-43e59d6b73a6?w=800&q=80&auto=format&fit=crop','Miso-glazed chickpeas with quinoa — a bowls recipe with ~14g protein per serving.',492,14,79,6,1,20,array['bowl','balanced'],array['chickpeas','quinoa','olive oil','seasoning','fresh herbs'],array['Prep and season the ingredients.','Cook the chickpeas.','Prepare the quinoa.','Plate, add herbs and serve.']),
('harissa-chickpeas-with-sweet-potato-91','Harissa chickpeas with sweet potato','Bowls','https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800&q=80&auto=format&fit=crop','Harissa chickpeas with sweet potato — a bowls recipe with ~14g protein per serving.',385,14,67,6,1,20,array['bowl','balanced'],array['chickpeas','sweet potato','olive oil','seasoning','fresh herbs'],array['Prep and season the ingredients.','Cook the chickpeas.','Prepare the sweet potato.','Plate, add herbs and serve.']),
('grilled-prawns-with-brown-rice-92','Grilled prawns with brown rice','Bowls','https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=800&q=80&auto=format&fit=crop','Grilled prawns with brown rice — a bowls recipe with ~24g protein per serving.',338,24,46,2,1,20,array['bowl','balanced'],array['prawns','brown rice','olive oil','seasoning','fresh herbs'],array['Prep and season the ingredients.','Cook the prawns.','Prepare the brown rice.','Plate, add herbs and serve.']),
('herb-roasted-prawns-with-quinoa-93','Herb-roasted prawns with quinoa','Bowls','https://images.unsplash.com/photo-1543339308-43e59d6b73a6?w=800&q=80&auto=format&fit=crop','Herb-roasted prawns with quinoa — a bowls recipe with ~24g protein per serving.',344,24,40,2,1,20,array['bowl','balanced'],array['prawns','quinoa','olive oil','seasoning','fresh herbs'],array['Prep and season the ingredients.','Cook the prawns.','Prepare the quinoa.','Plate, add herbs and serve.']),
('teriyaki-prawns-with-sweet-potato-94','Teriyaki prawns with sweet potato','Bowls','https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800&q=80&auto=format&fit=crop','Teriyaki prawns with sweet potato — a bowls recipe with ~24g protein per serving.',237,24,28,2,1,20,array['bowl','balanced'],array['prawns','sweet potato','olive oil','seasoning','fresh herbs'],array['Prep and season the ingredients.','Cook the prawns.','Prepare the sweet potato.','Plate, add herbs and serve.']),
('grilled-grilled-chicken-with-mixed-greens-95','Grilled grilled chicken with mixed greens','Salads','https://images.unsplash.com/photo-1540420773420-3366772f4999?w=800&q=80&auto=format&fit=crop','Grilled grilled chicken with mixed greens — a salads recipe with ~32g protein per serving.',203,32,8,5,1,20,array['salad','light'],array['grilled chicken','mixed greens','olive oil','seasoning','fresh herbs'],array['Prep and season the ingredients.','Cook the grilled chicken.','Prepare the mixed greens.','Plate, add herbs and serve.']),
('herb-roasted-grilled-chicken-with-roasted-veg-96','Herb-roasted grilled chicken with roasted veg','Salads','https://images.unsplash.com/photo-1546793665-c74683f339c1?w=800&q=80&auto=format&fit=crop','Herb-roasted grilled chicken with roasted veg — a salads recipe with ~32g protein per serving.',269,32,20,5,1,20,array['salad','light'],array['grilled chicken','roasted veg','olive oil','seasoning','fresh herbs'],array['Prep and season the ingredients.','Cook the grilled chicken.','Prepare the roasted veg.','Plate, add herbs and serve.']),
('teriyaki-prawns-with-mixed-greens-97','Teriyaki prawns with mixed greens','Salads','https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800&q=80&auto=format&fit=crop','Teriyaki prawns with mixed greens — a salads recipe with ~24g protein per serving.',152,24,7,2,1,20,array['salad','light'],array['prawns','mixed greens','olive oil','seasoning','fresh herbs'],array['Prep and season the ingredients.','Cook the prawns.','Prepare the mixed greens.','Plate, add herbs and serve.']),
('garlic-butter-prawns-with-roasted-veg-98','Garlic-butter prawns with roasted veg','Salads','https://images.unsplash.com/photo-1540420773420-3366772f4999?w=800&q=80&auto=format&fit=crop','Garlic-butter prawns with roasted veg — a salads recipe with ~24g protein per serving.',218,24,19,2,1,20,array['salad','light'],array['prawns','roasted veg','olive oil','seasoning','fresh herbs'],array['Prep and season the ingredients.','Cook the prawns.','Prepare the roasted veg.','Plate, add herbs and serve.']),
('cajun-chickpeas-with-mixed-greens-99','Cajun chickpeas with mixed greens','Salads','https://images.unsplash.com/photo-1546793665-c74683f339c1?w=800&q=80&auto=format&fit=crop','Cajun chickpeas with mixed greens — a salads recipe with ~14g protein per serving.',300,14,46,6,1,20,array['salad','light'],array['chickpeas','mixed greens','olive oil','seasoning','fresh herbs'],array['Prep and season the ingredients.','Cook the chickpeas.','Prepare the mixed greens.','Plate, add herbs and serve.']),
('mediterranean-chickpeas-with-roasted-veg-100','Mediterranean chickpeas with roasted veg','Salads','https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800&q=80&auto=format&fit=crop','Mediterranean chickpeas with roasted veg — a salads recipe with ~14g protein per serving.',366,14,58,6,1,20,array['salad','light'],array['chickpeas','roasted veg','olive oil','seasoning','fresh herbs'],array['Prep and season the ingredients.','Cook the chickpeas.','Prepare the roasted veg.','Plate, add herbs and serve.']),
('sesame-ginger-white-fish-with-mixed-greens-101','Sesame-ginger white fish with mixed greens','Salads','https://images.unsplash.com/photo-1540420773420-3366772f4999?w=800&q=80&auto=format&fit=crop','Sesame-ginger white fish with mixed greens — a salads recipe with ~26g protein per serving.',161,26,6,3,1,20,array['salad','light'],array['white fish','mixed greens','olive oil','seasoning','fresh herbs'],array['Prep and season the ingredients.','Cook the white fish.','Prepare the mixed greens.','Plate, add herbs and serve.']),
('lemon-pepper-white-fish-with-roasted-veg-102','Lemon-pepper white fish with roasted veg','Salads','https://images.unsplash.com/photo-1546793665-c74683f339c1?w=800&q=80&auto=format&fit=crop','Lemon-pepper white fish with roasted veg — a salads recipe with ~26g protein per serving.',227,26,18,3,1,20,array['salad','light'],array['white fish','roasted veg','olive oil','seasoning','fresh herbs'],array['Prep and season the ingredients.','Cook the white fish.','Prepare the roasted veg.','Plate, add herbs and serve.']),
('smoky-bbq-eggs-with-mixed-greens-103','Smoky BBQ eggs with mixed greens','Salads','https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800&q=80&auto=format&fit=crop','Smoky BBQ eggs with mixed greens — a salads recipe with ~18g protein per serving.',245,18,8,15,1,20,array['salad','light'],array['eggs','mixed greens','olive oil','seasoning','fresh herbs'],array['Prep and season the ingredients.','Cook the eggs.','Prepare the mixed greens.','Plate, add herbs and serve.']),
('peri-peri-eggs-with-roasted-veg-104','Peri-peri eggs with roasted veg','Salads','https://images.unsplash.com/photo-1540420773420-3366772f4999?w=800&q=80&auto=format&fit=crop','Peri-peri eggs with roasted veg — a salads recipe with ~18g protein per serving.',311,18,20,15,1,20,array['salad','light'],array['eggs','roasted veg','olive oil','seasoning','fresh herbs'],array['Prep and season the ingredients.','Cook the eggs.','Prepare the roasted veg.','Plate, add herbs and serve.']),
('protein-oats-with-berries-105','Protein oats with berries','Breakfast','https://images.unsplash.com/photo-1484723091739-30a097e8f929?w=800&q=80&auto=format&fit=crop','Protein oats with berries — a breakfast recipe with ~0g protein per serving.',70,0,17,0,1,10,array['breakfast','high-protein'],array['oats','berries','olive oil','seasoning','fresh herbs'],array['Prep and season the ingredients.','Cook the oats.','Prepare the berries.','Plate, add herbs and serve.']),
('veggie-scramble-106','Veggie scramble','Breakfast','https://images.unsplash.com/photo-1533089860892-a7c6f0a88666?w=800&q=80&auto=format&fit=crop','Veggie scramble — a breakfast recipe with ~18g protein per serving.',311,18,20,15,1,10,array['breakfast','low-carb'],array['eggs','roasted veg','olive oil','seasoning','fresh herbs'],array['Prep and season the ingredients.','Cook the eggs.','Prepare the roasted veg.','Plate, add herbs and serve.']),
('overnight-oats-107','Overnight oats','Breakfast','https://images.unsplash.com/photo-1525351484163-7529414344d8?w=800&q=80&auto=format&fit=crop','Overnight oats — a breakfast recipe with ~0g protein per serving.',105,0,27,0,1,10,array['breakfast'],array['oats','banana','olive oil','seasoning','fresh herbs'],array['Prep and season the ingredients.','Cook the oats.','Prepare the banana.','Plate, add herbs and serve.']),
('cottage-cheese-toast-108','Cottage cheese toast','Breakfast','https://images.unsplash.com/photo-1484723091739-30a097e8f929?w=800&q=80&auto=format&fit=crop','Cottage cheese toast — a breakfast recipe with ~24g protein per serving.',423,24,36,5,1,10,array['breakfast','high-protein'],array['cottage cheese','avocado toast','olive oil','seasoning','fresh herbs'],array['Prep and season the ingredients.','Cook the cottage cheese.','Prepare the avocado toast.','Plate, add herbs and serve.']),
('tofu-breakfast-scramble-109','Tofu breakfast scramble','Breakfast','https://images.unsplash.com/photo-1533089860892-a7c6f0a88666?w=800&q=80&auto=format&fit=crop','Tofu breakfast scramble — a breakfast recipe with ~18g protein per serving.',429,18,34,9,1,10,array['breakfast','vegan'],array['tofu','avocado toast','olive oil','seasoning','fresh herbs'],array['Prep and season the ingredients.','Cook the tofu.','Prepare the avocado toast.','Plate, add herbs and serve.']),
('greek-yogurt-parfait-110','Greek yogurt parfait','Breakfast','https://images.unsplash.com/photo-1525351484163-7529414344d8?w=800&q=80&auto=format&fit=crop','Greek yogurt parfait — a breakfast recipe with ~17g protein per serving.',206,17,25,4,1,10,array['breakfast'],array['greek yogurt','berries','olive oil','seasoning','fresh herbs'],array['Prep and season the ingredients.','Cook the greek yogurt.','Prepare the berries.','Plate, add herbs and serve.']),
('berry-protein-smoothie-111','Berry protein smoothie','Smoothies','https://images.unsplash.com/photo-1502741224143-90386d7f8c82?w=800&q=80&auto=format&fit=crop','Berry protein smoothie — a smoothies recipe with ~25g protein per serving.',200,25,20,2,1,5,array['smoothie','post-workout'],array['whey protein','berries','olive oil','seasoning','fresh herbs'],array['Prep and season the ingredients.','Cook the whey protein.','Prepare the berries.','Plate, add herbs and serve.']),
('banana-peanut-shake-112','Banana peanut shake','Smoothies','https://images.unsplash.com/photo-1553530666-ba11a7da3888?w=800&q=80&auto=format&fit=crop','Banana peanut shake — a smoothies recipe with ~25g protein per serving.',235,25,30,2,1,5,array['smoothie'],array['whey protein','banana','olive oil','seasoning','fresh herbs'],array['Prep and season the ingredients.','Cook the whey protein.','Prepare the banana.','Plate, add herbs and serve.']),
('green-recovery-smoothie-113','Green recovery smoothie','Smoothies','https://images.unsplash.com/photo-1610970881699-44a5587cabec?w=800&q=80&auto=format&fit=crop','Green recovery smoothie — a smoothies recipe with ~17g protein per serving.',241,17,35,4,1,5,array['smoothie'],array['greek yogurt','banana','olive oil','seasoning','fresh herbs'],array['Prep and season the ingredients.','Cook the greek yogurt.','Prepare the banana.','Plate, add herbs and serve.']),
('chocolate-whey-shake-114','Chocolate whey shake','Smoothies','https://images.unsplash.com/photo-1502741224143-90386d7f8c82?w=800&q=80&auto=format&fit=crop','Chocolate whey shake — a smoothies recipe with ~25g protein per serving.',280,25,30,2,1,5,array['smoothie','post-workout'],array['whey protein','oats','olive oil','seasoning','fresh herbs'],array['Prep and season the ingredients.','Cook the whey protein.','Prepare the oats.','Plate, add herbs and serve.']),
('greek-yogurt-berries-115','Greek yogurt & berries','Snacks','https://images.unsplash.com/photo-1490474418585-ba9bad8fd0ea?w=800&q=80&auto=format&fit=crop','Greek yogurt & berries — a snacks recipe with ~17g protein per serving.',206,17,25,4,1,5,array['snack','high-protein'],array['greek yogurt','berries','olive oil','seasoning','fresh herbs'],array['Prep and season the ingredients.','Cook the greek yogurt.','Prepare the berries.','Plate, add herbs and serve.']),
('hummus-veg-116','Hummus & veg','Snacks','https://images.unsplash.com/photo-1505253758473-96b7015fcd40?w=800&q=80&auto=format&fit=crop','Hummus & veg — a snacks recipe with ~14g protein per serving.',366,14,58,6,1,5,array['snack','vegan'],array['chickpeas','roasted veg','olive oil','seasoning','fresh herbs'],array['Prep and season the ingredients.','Cook the chickpeas.','Prepare the roasted veg.','Plate, add herbs and serve.']),
('cottage-cheese-bowl-117','Cottage cheese bowl','Snacks','https://images.unsplash.com/photo-1571091718767-18b5b1457add?w=800&q=80&auto=format&fit=crop','Cottage cheese bowl — a snacks recipe with ~24g protein per serving.',233,24,23,5,1,5,array['snack'],array['cottage cheese','berries','olive oil','seasoning','fresh herbs'],array['Prep and season the ingredients.','Cook the cottage cheese.','Prepare the berries.','Plate, add herbs and serve.']),
('hard-boiled-eggs-118','Hard-boiled eggs','Snacks','https://images.unsplash.com/photo-1490474418585-ba9bad8fd0ea?w=800&q=80&auto=format&fit=crop','Hard-boiled eggs — a snacks recipe with ~18g protein per serving.',215,18,2,15,1,5,array['snack','low-carb'],array['eggs','olive oil','seasoning','fresh herbs'],array['Prep and season the ingredients.','Cook the eggs.','Assemble.','Plate, add herbs and serve.']),
('lentil-veg-soup-119','Lentil & veg soup','Soups','https://images.unsplash.com/photo-1476718406336-bb5a9690ee2a?w=800&q=80&auto=format&fit=crop','Lentil & veg soup — a soups recipe with ~18g protein per serving.',337,18,58,1,4,30,array['soup','vegan'],array['lentils','roasted veg','olive oil','seasoning','fresh herbs'],array['Prep and season the ingredients.','Cook the lentils.','Prepare the roasted veg.','Plate, add herbs and serve.']),
('chicken-quinoa-soup-120','Chicken & quinoa soup','Soups','https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?w=800&q=80&auto=format&fit=crop','Chicken & quinoa soup — a soups recipe with ~35g protein per serving.',398,35,39,4,4,30,array['soup','high-protein'],array['chicken breast','quinoa','olive oil','seasoning','fresh herbs'],array['Prep and season the ingredients.','Cook the chicken breast.','Prepare the quinoa.','Plate, add herbs and serve.']),
('black-bean-soup-121','Black bean soup','Soups','https://images.unsplash.com/photo-1547592166-23ac45744acd?w=800&q=80&auto=format&fit=crop','Black bean soup — a soups recipe with ~15g protein per serving.',338,15,59,2,4,30,array['soup','vegan'],array['black beans','roasted veg','olive oil','seasoning','fresh herbs'],array['Prep and season the ingredients.','Cook the black beans.','Prepare the roasted veg.','Plate, add herbs and serve.']),
('protein-mug-cake-122','Protein mug cake','Desserts','https://images.unsplash.com/photo-1488477181946-6428a0291777?w=800&q=80&auto=format&fit=crop','Protein mug cake — a desserts recipe with ~25g protein per serving.',280,25,30,2,2,15,array['dessert','high-protein'],array['whey protein','oats','olive oil','seasoning','fresh herbs'],array['Prep and season the ingredients.','Cook the whey protein.','Prepare the oats.','Plate, add herbs and serve.']),
('yogurt-bark-123','Yogurt bark','Desserts','https://images.unsplash.com/photo-1505253716362-afaea1d3d1af?w=800&q=80&auto=format&fit=crop','Yogurt bark — a desserts recipe with ~17g protein per serving.',206,17,25,4,2,15,array['dessert'],array['greek yogurt','berries','olive oil','seasoning','fresh herbs'],array['Prep and season the ingredients.','Cook the greek yogurt.','Prepare the berries.','Plate, add herbs and serve.']),
('banana-protein-cookies-124','Banana protein cookies','Desserts','https://images.unsplash.com/photo-1551024601-bec78aea704b?w=800&q=80&auto=format&fit=crop','Banana protein cookies — a desserts recipe with ~25g protein per serving.',235,25,30,2,2,15,array['dessert'],array['whey protein','banana','olive oil','seasoning','fresh herbs'],array['Prep and season the ingredients.','Cook the whey protein.','Prepare the banana.','Plate, add herbs and serve.'])
on conflict (slug) do nothing;
